task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/nery_neto_bemagro_com/datasets/residue_augmented-12-5/train/images
    ann_file: /home/nery_neto_bemagro_com/datasets/residue_augmented-12-5/train/annotations.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/nery_neto_bemagro_com/datasets/residue_augmented-12-5/val/images
    ann_file: /home/nery_neto_bemagro_com/datasets/residue_augmented-12-5/val/annotations.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 1
  num_workers: 1
  drop_last: False
