__include__: [
  '../dataset/residue.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_swin.yml'  # Base config
]

Swin:
  variant: tiny
  return_idx: [1, 2, 3]

output_dir: ./output/rtdetr_swin_tiny_6x_mask

HybridEncoder:
  in_channels: [192, 384, 768]
  feat_strides: [8, 16, 32]
  hidden_dim: 384
  dim_feedforward: 2048


RTDETRTransformer:
  feat_channels: [384, 384, 384]
  mask_head:
    type: MaskHead
    input_dim: 256
    hidden_dim: 256
    num_heads: 2


optimizer:
  type: AdamW
  params: 
    - 
      params: 'backbone'
      lr: 0.0001