__include__: [
  '../dataset/residue.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
    './include/rtdetr_r50vd_masks.yml',
]

PResNet:
  depth: 18
  
output_dir: ./output/rtdetr_r18vd_6x_mask



HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformer:
  feat_channels: [384, 384, 384]
  mask_head:
    type: MaskHead
    input_dim: 256
    hidden_dim: 256
    num_heads: 2


optimizer:
  type: AdamW
  params: 
    - 
      params: 'backbone'
      lr: 0.0001